# Generated by Django 3.0.5 on 2020-04-25 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='Phonenumber',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registration',
            name='Sitemoto',
            field=models.CharField(max_length=100),
        ),
    ]
