# Generated by Django 3.0.5 on 2020-05-03 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Slug',
            new_name='slug',
        ),
    ]
